server:
  port: 8084

eureka:
  instance:
    hostname: host.docker.internal
  server:
    enable-self-preservation: false
    # eureka\
    eviction-interval-timer-in-ms: 5000
  client:
    # eureka
    register-with-eureka: false
    fetch-registry: false



