server:
  port: 8082
  servlet:
    context-path: /item

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emart_item?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update