server:
  port: 8081
  servlet:
    context-path: /user

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emart_user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update