server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: emart-user
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/emart_user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8084/eureka/
    # 表示eureka client间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 5
  instance:
    instance-id:  ${spring.cloud.client.hostname}:${server.port}
#    instance-id:  ${spring.cloud.client.hostname}:${server.port}
    ip-address: host.docker.internal
    prefer-ip-address: true

#audience:
#  clientId: 2930409384859504
#  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
#  name: restapiuser
#  expiresSecond: 172800

logging:
  level:
    root: info