server:
  port: 8081
  servlet:
    context-path: /user

spring:
  application:
    name: emart-user
  datasource:
    url: jdbc:mysql://localhost:3306/emart_user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
    # 表示eureka client间隔多久去拉取服务注册信息
    registry-fetch-interval-seconds: 5
  instance:
    instance-id:  ${spring.cloud.client.hostname}:${server.port}