server:
  port: 8085

spring:
  application:
    name: emart-zuul

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8084/eureka/
    # eureka client
    registry-fetch-interval-seconds: 5
  instance:
    instance-id:  ${spring.cloud.client.hostname}:${server.port}:${spring.application.name}:@project.version@
    ip-address: 127.0.0.1
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000
  hystrix:
    enabled: false
